# Generated by Django 5.0 on 2024-04-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_alter_code_guide_alter_code_seller_alter_code_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_guide', to='registration.guide')),
                ('receiver_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_seller', to='registration.seller')),
                ('receiver_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='registration.user')),
                ('sender_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_guide', to='registration.guide')),
                ('sender_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_seller', to='registration.seller')),
                ('sender_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='registration.user')),
            ],
        ),
    ]
