# Generated by Django 4.1.7 on 2024-04-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('identifier', models.CharField(default='localevents', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='event')),
                ('tag', models.TextField(null=True)),
            ],
        ),
    ]
