# Generated by Django 5.0 on 2024-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_title_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='identifier',
            field=models.CharField(default='localevents', max_length=50),
        ),
    ]
