# Generated by Django 5.0 on 2024-04-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startpoint', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=50)),
                ('vehicleName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppoint', models.CharField(max_length=50)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoppoint_transportation', to='transportation.transportation')),
            ],
        ),
    ]
