# Generated by Django 5.0 on 2024-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('tag', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='place')),
                ('identifier', models.CharField(default='place', max_length=50)),
            ],
        ),
    ]
