# Generated by Django 5.0 on 2024-03-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to='place'),
        ),
    ]
