# Generated by Django 5.0 on 2024-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.TextField(null=True),
        ),
    ]
