# Generated by Django 5.0 on 2024-04-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guidefind', '0002_guiderequirement_budget'),
        ('guidehire', '0002_guidehire_date'),
        ('registration', '0003_alter_code_guide_alter_code_seller_alter_code_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_guide', to='registration.guide')),
                ('guidehire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_guidehire', to='guidehire.guidehire')),
                ('guidereq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_guidereq', to='guidefind.guiderequirementhiring')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='registration.seller')),
            ],
        ),
    ]
