# Generated by Django 4.1.7 on 2024-04-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('address', models.TextField()),
                ('location', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='hotel')),
                ('rating', models.IntegerField(default=0)),
                ('noOfRoom', models.IntegerField()),
                ('identifier', models.CharField(default='hotel', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_seller', to='registration.seller')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=50)),
                ('roomPrice', models.IntegerField()),
                ('roomImage', models.ImageField(null=True, upload_to='hotel_room')),
                ('roomDescription', models.TextField()),
                ('roomNo', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='hotelbooking.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'roomNo')},
            },
        ),
        migrations.CreateModel(
            name='HotelRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('amount', models.IntegerField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_room_hb', to='hotelbooking.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_user_hb', to='registration.seller')),
            ],
        ),
    ]
