# Generated by Django 5.0 on 2024-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroombooking',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
