# Generated by Django 5.0 on 2024-04-14 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0004_alter_hotelroom_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroombooking',
            name='amount',
        ),
    ]
