# Generated by Django 5.0 on 2024-04-14 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_remove_hotelroombooking_amount'),
        ('registration', '0003_alter_code_guide_alter_code_seller_alter_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroombooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking_user_hb', to='registration.user'),
        ),
    ]
