# Generated by Django 5.0 on 2024-03-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='shop')),
                ('rating', models.IntegerField(default=0)),
                ('identifier', models.CharField(default='shop', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_seller', to='registration.seller')),
            ],
        ),
    ]
