# Generated by Django 5.0 on 2024-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
