# Generated by Django 5.0 on 2024-04-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rating',
        ),
    ]
