# Generated by Django 5.0 on 2024-03-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(null=True, upload_to='guide'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to='seller'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
