# Generated by Django 5.0 on 2024-04-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='sellertype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expiry', models.DateTimeField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.guide')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
