# Generated by Django 5.0 on 2024-03-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('status', models.CharField(default='ongoing', max_length=50)),
                ('day', models.IntegerField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireguide', to='registration.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hireuser', to='registration.user')),
            ],
        ),
    ]
