# Generated by Django 5.0 on 2024-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidehire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidehire',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
