# Generated by Django 5.0 on 2024-04-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidehire', '0002_guidehire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidehire',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
